# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-DBStag
version:      0.10
version_from: DBIx/DBStag.pm
installdirs:  site
requires:
    Data::Stag:                    0.07
    DBI:                           0
    DBIx::DBSchema:                0.34
    Parse::RecDescent:             0
    Text::Balanced:                0
    XML::Parser::PerlSAX:          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
