#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-DBStag
version:      0.08
version_from: DBIx/DBStag.pm
installdirs:  site
requires:
    DBIx::DBSchema:                0
    Data::Stag:                    0.07
    Parse::RecDescent:             0
    XML::Parser::PerlSAX:          0
    Text::Balanced:                0
    DBI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
