--- #YAML:1.0
name:               DBIx-DBStag
version:            0.11
abstract:           DBStag
author:
    - Chris Mungall <cjm@fruitfly.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Stag:           0.07
    DBI:                  0
    DBIx::DBSchema:       0.34
    Parse::RecDescent:    0
    Text::Balanced:       0
    XML::Parser::PerlSAX:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
