#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-DBStag
version:      0.05
version_from: DBIx/DBStag.pm
installdirs:  site
requires:
    DBI:                           0
    DBIx::DBSchema:                0
    Parse::RecDescent:             0
    Data::Stag:                    0.06
    Text::Balanced:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
